### ISSUE TITLE
Urls with extra hyphens not working after import

### ISSUE THREAD

**Issue by kunwarsaluja** [aemsites/hubblehomes-com#177]
We might need to handle urls with extra hyphens in the url as they are being sanitized while import

See example https://www.hubblehomes.com/news/news-detail/2022-hero-house-charities-idaho-humane-society--111

Post import : https://main--hubblehomes-com--aemsites.hlx.page/news/news-detail/2022-hero-house-charities-idaho-humane-society-111 (**_Note the extra hyphen --111_**)

Either we somehow handle such urls at the time of import or  in redirect sheet or on the CDN level

**Comment by bhellema** [comment]
I don't think we need to do anything here.  It seems as though hubblehomes back end system doesn't care about the URL structure for pages under /news/news-details/  It seems as though looking to serve up the page the system throws away everything after /news-details except the last characters after the -- or /.

For example: https://www.hubblehomes.com/news/news-detail/12l3j21l3j12j3l12312l3klj12l3j12kl3jl12j3lj12l123l3l2-110 and 
https://www.hubblehomes.com/news/news-detail/12l3j21l3j12j3l12312l3klj12l3j12kl3jl12j3lj12l123l3l2/110 both work.  It seems as longs as it can locate article 110 in the scenario, it will serve it up otherwise the system redirects to the home page.

**Comment by varunmitra** [comment]
based on slack conversation: The URL doesn't represent actual content. numeric value at the end of URL maps to the actual article. As long as the value is present indexing would do it's job eg. https://www.hubblehomes.com/news/news-detail/113 <-- that's the article number and the back end uses this to figure out via the index.
